<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="HomeBudget.Web.Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <div style="display: block; position: relative; float: left; width: 300px;">
            <div>
                <h2>
                    List of Accounts</h2>
            </div>
            <div>
                <h3>
                    Add new record:</h3>
                <br />
                <asp:Label ID="lblAccountName" runat="server" Text="Account name:"></asp:Label>
                <asp:TextBox ID="txtAccountName" runat="server"></asp:TextBox>
                <asp:Button ID="btnAddNewAccount" runat="server" Text="Add new account" OnClick="btnAddNewAccount_Click" />
                <div>
                    <asp:Label ID="lblAddNewAccountError" runat="server" Text="" Visible="false" ForeColor="Red"></asp:Label>
                </div>
            </div>
            <br />
            <div>
                <asp:ObjectDataSource ID="AccountDataSource" runat="server" SelectMethod="GetAllAccounts"
                    InsertMethod="AddAccount" UpdateMethod="UpdateAccount" DataObjectTypeName="HomeBudget.Domain.Entities.Account"
                    TypeName="HomeBudget.Domain.Services.AccountService" OnObjectCreating="AccountDataSource_ObjectCreating">
                </asp:ObjectDataSource>
                <asp:GridView ID="gvAccount" runat="server" DataSourceID="AccountDataSource" AllowPaging="False"
                    AutoGenerateEditButton="True" ShowHeaderWhenEmpty="True" AutoGenerateSelectButton="True"
                    AutoGenerateDeleteButton="True" DataKeyNames="AccountId">
                </asp:GridView>
            </div>
        </div>
        <div style="display: block; position: relative; float: left;">
            <div>
                <h2>
                    Registred receipts</h2>
            </div>
            <div>
                <h3>
                    Add new receipt:</h3>
                <br />
                <asp:Label ID="lblReceiptAmount" runat="server" Text="Amount:"></asp:Label>
                <asp:TextBox ID="txtReceiptAmount" runat="server"></asp:TextBox><br />
                <asp:Label ID="lblReceiptDescription" runat="server" Text="Description:"></asp:Label>
                <asp:TextBox ID="txtReceiptDescription" runat="server"></asp:TextBox><br />
                <asp:Button ID="btnAddNewReceipt" runat="server" Text="Add new receipt" OnClick="btnAddNewReceipt_Click" />
                <div>
                    <asp:Label ID="lblAddNewReceiptError" runat="server" Text="" Visible="false" ForeColor="Red"></asp:Label>
                </div>
            </div>
            <div>
                <asp:ObjectDataSource ID="ReceiptDataSource" runat="server" SelectMethod="GetReceiptsForAccount"
                    InsertMethod="AddReceipt" UpdateMethod="UpdateReceipt" DataObjectTypeName="HomeBudget.Domain.Entities.Receipt"
                    TypeName="HomeBudget.Domain.Services.ReceiptService" OnObjectCreating="ReceiptDataSource_ObjectCreating">
                    <SelectParameters>
                        <asp:Parameter Name="accountId" Type="Int64" DefaultValue="0"/>
                    </SelectParameters>
                </asp:ObjectDataSource>
                <asp:GridView ID="gvReceipt" runat="server" DataSourceID="ReceiptDataSource" AllowPaging="False"
                    AutoGenerateEditButton="True" ShowHeaderWhenEmpty="True" AutoGenerateSelectButton="True"
                    AutoGenerateDeleteButton="True" DataKeyNames="ReceiptId">
                </asp:GridView>
            </div>
        </div>
    </div>
    </form>
</body>
</html>
